### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by ShadowGreg** [danheron/Heron.MudCalendar#100]
Failed to load resource: the server responded with a status of 404 ()  content/Heron.MudCalendar/Heron.MudCalendar.js:1   Failed to load resource: the server responded with a status of 404 ()

**Comment by miguelmachado17** [comment]
Hello,

I was having the same problem and notice that a **Heron.MudCalendar.min.js** was loading, so I just changed the code below and stopped having the error.

`<script src="_content/Heron.MudCalendar/Heron.MudCalendar.js"></script>`

To

`<script src="_content/Heron.MudCalendar/Heron.MudCalendar.min.js"></script>`

**Comment by danheron** [comment]
Thanks, I will update the documentation.
