### ISSUE TITLE
Async updates

### ISSUE THREAD

**Issue by nlough** [danheron/Heron.MudCalendar#103]
I'm trying to show a loading... indicator when the DateRangeChange event is triggered - until my data load is complete. To get the UI to behave in that way I seemingly have to mark the DateRangeChange event as async. Initially that appears to be fine. The issue I have however is that when the user then attempts to navigate to another month using say the back/forward arrow on the control,  the UI on the calendar doesn't then refresh. The new daterange is correctly passed to the DateRangeChange event, the data is retrieved but the calendar still shows the original month/dates. Have tried calling StateHasChanged as well as the Refresh method for the calendar itself. Any advice would be appreciated. Apologies in advance if this is the wrong place to post.

**Comment by danheron** [comment]
I've tried loading events from a web service with 2 second delay, but it all seems to work fine for me.

If you want to send me an example project showing the problem then I will take a look at it.

**Comment by danheron** [comment]
Closing because no reply.
