### ISSUE TITLE
Option to exclude certain days

### ISSUE THREAD

**Issue by os-dmi** [danheron/Heron.MudCalendar#105]
A common usage of this would be the ability to remove weekend days (typically Saturday and Sunday) from the calendar.

Can be expanded to more generalized exclusion patterns (also on weeks or months).

**Comment by os-dmi** [comment]
Update: I managed to implement this by using a custom MonthView, but it required some copy & pasting of the original code and changing of hard-coded magic numbers.

**Comment by danheron** [comment]
This issue was resolved with #121.
