### ISSUE TITLE
 Calendar items truncated in day and week view

### ISSUE THREAD

**Issue by oh-cheezburgers** [danheron/Heron.MudCalendar#108]
**Description:**
When viewing calendar items in the day or week view, some items are either missing or only partly rendering. Upon further investigation, it was observed that calendar items which are less than the `CalendarTimeInterval` are being truncated.

**Steps to Reproduce:**
1. Navigate to the day or week view of the calendar.
2. Observe calendar items, especially those with a duration less than `CalendarTimeInterval`.

**Expected Behavior:**
All calendar items, regardless of their duration, should render fully within the designated time slots.

**Actual Behavior:**
Calendar items with a duration less than `CalendarTimeInterval` are truncated or missing in the day or week view.

**Screenshots:**
1. ![Screenshot 1](https://github.com/danheron/Heron.MudCalendar/assets/3510774/a44994d1-ad8f-4ff6-8279-11aa8822a809)
2. ![Screenshot 2](https://github.com/danheron/Heron.MudCalendar/assets/3510774/f215c5ed-650a-44e9-8adc-68e661b4d339)

**Additional Information:**
When inspecting the items using Chrome Developer tools, a div with a fixed height and an overflow property set to hidden can be observed. Removing the overflow property resolves the issue, allowing the item to render fully.

**Environment:**
- Browser: Chrome 124.0.6367.63
- Heron.MudCalendar: 1.1.1

**Comment by danheron** [comment]
It was made by design that the height of the calendar item = the duration of the item.  However I see that with very short durations it doesn't work very well.  I will review it.

**Comment by danheron** [comment]
I will add a new property ```DayItemMinHeight```

If you set this to the same height as the ```DayCellHeight``` (default = 36) then it should do what you want.

**Comment by oh-cheezburgers** [comment]
That's brilliant, thank you!
