### ISSUE TITLE
Is there a way for the calendar to start on another day that is not Sunday? eg: Monday?

### ISSUE THREAD

**Issue by vcdotwine** [danheron/Heron.MudCalendar#111]
I am looking to give users the ability to change the day their week starts. Any ideas on how to achieve this?

Thanks!

**Comment by danheron** [comment]
It takes the first day of the week from the culture settings:

```C#
var firstDay = CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek;
```

If you change the culture it will change the day the week starts.

**Comment by vcdotwine** [comment]
Thanks Dan!
