### ISSUE TITLE
Calendar broke after 1.0.4 update

### ISSUE THREAD

**Issue by Pvxtotal** [danheron/Heron.MudCalendar#12]
![image](https://user-images.githubusercontent.com/50109738/232083811-e03be9d2-fa10-4733-bbd3-9e105e7c85e9.png)

Hi! Thank you for fixing issue #9 .

Unfortunately after updating to 1.0.4 my calendar looks like this. Can you help me?

**Comment by danheron** [comment]
It looks like some styles are missing.  But it looks more like a MudBlazor problem than a MudCalendar problem.  If you were just missing the MudCalendar styles then the buttons would still look correct.

Did you upgrade the version of MudBlazor you are using?  Maybe your browser has cached an older version of the MudBlazor stylesheet.

**Comment by danheron** [comment]
You don't need to downgrade MudBlazor - just make sure the stylesheet isn't cached. e.g. my clearing the browser cache.

Does the rest of your application still work?  Do other MudBlazor components still look OK?

Can you tell me:
Are you musing Blazor wasm or server?
Are you using .Net 6 or 7?

**Comment by Pvxtotal** [comment]
> You don't need to downgrade MudBlazor - just make sure the stylesheet isn't cached. e.g. by clearing the browser cache.
> 
> Does the rest of your application still work? Do other MudBlazor components still look OK?
> 
> Can you tell me: Are you using Blazor wasm or server? Are you using .Net 6 or 7?

Blazor Server - .NET 7

The rest of application looks good. Everything's OK.

I tried to clear cache, I tried to open in private tabs, same result.

If I downgrade MudCalendar to 1.0.3 it goes back to normal.

**Comment by danheron** [comment]
That's very strange.  I created a new .Net 7 server project and it's working fine.

Is it possible to put your application online so that I can look at it?  Or if you want to send me the source code I will try to find what the problem is.
