### ISSUE TITLE
Work Week view 

### ISSUE THREAD

**Issue by gabriuz** [danheron/Heron.MudCalendar#121]
Hello,

I would like to use MudCalendar for work planning. Usually the work is done on work days only - excluding Saturday and Sunday, so we can save some horizontal space and display more data in a cell.

This feature request relates to a previous one:  https://github.com/danheron/Heron.MudCalendar/issues/105

Though here I would like to get a fourth button (work week, customizable/translated)  in addition to existing _month, week, day_ views.

If that makes sense, I could contribute and make a pull request:

- new parameter to show Work Week view button (hidden by default)
- updates to WorkView component
- translations
- test updates

**Comment by gabriuz** [comment]
Here's the pull request:
https://github.com/danheron/Heron.MudCalendar/pull/128

Looking forward to your comments.

**Comment by danheron** [comment]
Thanks!  That looks really good.

My only issue is with the new FirstDayOfWeek property.  It defaults to Sunday, but in my culture Monday is the first day of week.  So now I have the problem that the normal week view is starting on Sunday and the DatePicker also uses Sunday as the first day of week.

I think it would be better to make this property nullable and if null then use the current culture settings.  This is how the DatePicker in MudBlazor works:

![image](https://github.com/danheron/Heron.MudCalendar/assets/51314385/68fbf5fa-896c-4c56-97b0-840c56c0a8d4)

**Comment by gabriuz** [comment]
Hey,
https://github.com/danheron/Heron.MudCalendar/pull/128/commits/59182922922225d2598a2cf2b5495ae957453029
fixed FirstDayOfWeek property - now it works as previously if unset.
This fix also reverted some changes to old tests - that's nice.

**Comment by danheron** [comment]
Thanks for the updates, but I now have other problems:

1. The DatePicker doesn't work anymore, when I click on it I get an error.
2. There are build warnings:

![image](https://github.com/danheron/Heron.MudCalendar/assets/51314385/9bfc3dc8-da0a-4bb4-9557-2ab684d72264)

The warnings are only in the Unit Tests so not really critical, but it would still be good to fix these warnings.

**Comment by gabriuz** [comment]
Sorry for broken DatePicker, fixed now and the warnings are gone.
https://github.com/danheron/Heron.MudCalendar/pull/128/commits/6134b8f4bc4f8a52c56029426bd04cd0ed0062f6

**Comment by danheron** [comment]
Looks good!

**Comment by digitaldirk** [comment]
Hi thank you for this contribution,

In my case an offical week is sun-sat and a work week is mon-fri. (But some calendars show as sun-sat and some are mon-sun)

So with no configuration of the MudCalendar, the week view shows sun-sat which is correct but the work week view shows sun-thurs, which I expect to be mon-fri. If I set FirstDayOfWeek to monday then the work week is right mon-fri but the week is now mon-sun.

Could there be a FirstDayOfWorkWeek as well so I could achieve sun-sat for week and mon-fri for work week?

@gabriuz @danheron

**Comment by gabriuz** [comment]
Hi,

sure, if Dan agrees, I could prepare a PR with new FirstDayOfWorkWeek param.

**Comment by danheron** [comment]
Sounds good.  That would be great if you could create a PR @gabriuz.

**Comment by gabriuz** [comment]
Hello,

here's the PR: https://github.com/danheron/Heron.MudCalendar/pull/169
Looking forward to your comments!
