### ISSUE TITLE
When the ItemClicked event is enabled, a margin is added to the bottom of the page when Day view and Month view.

### ISSUE THREAD

**Issue by UMP45Mod** [danheron/Heron.MudCalendar#136]
Hello, When the ItemClicked event is enabled, a margin is added to the bottom of the page when Day view and Month view.

![HeronCalendar](https://github.com/danheron/Heron.MudCalendar/assets/72752397/c51115fb-68c5-42cf-9d58-ebae0ac65987)

**Comment by danheron** [comment]
Duplicate of #130.
