### ISSUE TITLE
Rendering seems broken in Blazor Hybrid

### ISSUE THREAD

**Issue by maxibyte** [danheron/Heron.MudCalendar#14]
First of all, I want to thank you for your awesome work! =)

![image](https://user-images.githubusercontent.com/69119625/232908634-a311034e-5ee4-4401-b516-77d50fa41371.png)

I have set up a clean .NET MAUI Blazor app project and the rendering is broken. In Blazor WASM everything is fine.

I'm using: 
- MudCalendar 1.0.5
- MudBlazor 6.2.2

Perhaps its somehow related to https://github.com/danheron/Heron.MudCalendar/issues/12

**Comment by danheron** [comment]
MudCalendar injects the stylesheet link into the head element when it is needed.  However this doesn't seem to work in Maui Blazor.

As a workaround you can just add the links to your index.html page in the same way as you do for MudBlazor:

<link href="_content/MudBlazor/MudBlazor.min.css" rel="stylesheet" />
<link href="_content/Heron.MudCalendar/Heron.MudCalendar.min.css" rel="stylesheet" />

<script src="_content/MudBlazor/MudBlazor.min.js"></script>
<script src="_content/Heron.MudCalendar/Heron.MudCalendar.js"></script>

**Comment by maxibyte** [comment]
I have added 

<link href="_content/Heron.MudCalendar/Heron.MudCalendar.min.css" rel="stylesheet" />

to my index.html and now everything is working fine. Thanks for the workaround.
