### ISSUE TITLE
Cannot assign custom item to the MudCalendar Items Parameter

### ISSUE THREAD

**Issue by ansab490** [danheron/Heron.MudCalendar#140]
Hi,

First of all thank you for building this component. I am currently ripping out the pure JS calendar for this as this is so much easier to integrate and use. 

However, I ran in to problem with custom content and I think this might be a bug

As per the documentation, we can create custom content to be displayed in cell. The approach is to create a class that needs to inherit from CalendarItem and then a cell template needs to be defined. I followed to exact approach, but I couldn't find new properties in the .razor class. 

On investigation,  I found out that the MudCalendar **_Items_** Parameter is not defined as _**IEnumerable(T)**_ but rather as _**IEnumerable(CalendarItem)**_ as shown below:

![MudCalendar Items](https://github.com/danheron/Heron.MudCalendar/assets/160683278/602824a7-695a-4152-8795-f86bd279b0b3)

This means that no matter what kind of class I give it. It doesn't matter.

Can you please have a look at this in your spare time?

P.S. If its me who is doing something wrong please let me know

Kind Regards
Ansab

**Comment by danheron** [comment]
Have you looked at the documentation?  The 'Custom Content' example shows how to do this.

I'm not sure what your problem is.  If you could show your code that isn't working then maybe I can be of more help.

**Comment by ansab490** [comment]
Yup followed the documentation word by word. 
Created a class, that inherits from CalendarItem class. Added 2 extra properties Color and Text2
when I assign that to the Items property in the mud calendar the new properties doesn't show up in .razor file. Only the properties defined in the CalendarItem come up

**Comment by ansab490** [comment]
Alright, I will close this issue. I have no idea, what is happening. I tried yesterday, it was not working for me. Today, I just did it all again and its working. I am sorry about that, maybe I missed out on something yesterday.
