### ISSUE TITLE
Current Time Marker not rendering

### ISSUE THREAD

**Issue by APusch-Tenno** [danheron/Heron.MudCalendar#142]
Hi again,

while checking for a refresh of the calendar (will probably open another issue about that), I noticed that the current time marker isn't there anymore.

the problem is, I don't know when it disappeared and since the firefox fix, I haven't done any manual changes in the MudCalendar project.

I have set ShowCurrentTime=true and checked for possible differences in my code, but so far it seems identical to the code on GitHub (except for that localization fix, where I just divided the interval by 2, so the marker was actually on the right position for my time zone).

When I load your solution I see the line on CalendarTimeIntervalTest, so its not a general browser issue.

When I insert an empty IF where the line is drawn, it actually jumps in there multiple times while loading the week.
I even replaced the hr with a MudDivider, but there is still no line.

I was thinking, that the line might be there, but is rendering somewhere outside the visible area, but I don't know how to manually set it to a specific time to check that.

Could you point me in the right direction what else I could check?

**Comment by danheron** [comment]
I don't know what to suggest.  Like you say it works in my solution both in the unit tests and the docs.

Make sure your css files are up to date and not being cached by the browser.

If you think it might be rendering outside the visible area then open your browser dev tools and search for it.  It's an hr element with the class name mud-cal-current-time.

**Comment by APusch-Tenno** [comment]
I checked that and apparently it is there, but showing 0 pixel height!?

![grafik](https://github.com/user-attachments/assets/c3e7125c-a881-453f-be93-57455cf258d0)

If the blue dashed line is supposed to be the position, its also not correct again, because it was already past 9 am.

**Comment by danheron** [comment]
I don't know what you expect from me.  You have changed the code and now it doesn't work.  I can't see your code so how can I know why it's not working.

Try using the latest nuget package (2.0.0).  If there is a problem with it then either explain how I can recreate the problem or send an example project showing the problem.
