### ISSUE TITLE
Mudcalendar Wiki - API section not loading

### ISSUE THREAD

**Issue by ansab490** [danheron/Heron.MudCalendar#147]
Hi again,

I was just looking at some properties for the MudCalendar and tried to access the documentation. I can see the content for Example and Extending menu items. However, I get blank screen for API menu item. See screenshot below:
![image](https://github.com/user-attachments/assets/5eeacc2f-b5f9-4f6b-ab67-b64752010e7e)

I tried Firefox, Chrome and Edge, all with the same result. Has this page been taken down? 

P.S. I don't see any error on the browser console, so its' definitely not breaking at render

Thanks

**Comment by danheron** [comment]
This is fixed now.

**Comment by ansab490** [comment]
Thanks for that
