### ISSUE TITLE
CalendarItem

### ISSUE THREAD

**Issue by fabiofastech** [danheron/Heron.MudCalendar#153]
I would suggest adding a couple of additional properties to the CalendarItem class, for example the ability to set the appointment color both as standard colors (Color.Default, Color.Success etc.) and as palette colors (Colors.Purple.Lighten3, Colors.Green. Darken2, etc.) => "COLOR" field.
A "CATEGORY" field can also be added.
Finally I would say that it would be extremely useful to add an object attached to the CalendarItem Class => CalendarItem<T>

**Comment by danheron** [comment]
I don't think there is any need for this.  You can already create your own class that inherits from CalendarItem and includes any properties that you want.

The 'Custom Content' example in the documents shows how to do this.

**Comment by fabiofastech** [comment]
You're right, it's clear that I didn't read the documentation carefully enough!
