### ISSUE TITLE
Expose FixDay/FixMonth/FixDay and OpenTo Discussion

### ISSUE THREAD

**Issue by digitaldirk** [danheron/Heron.MudCalendar#155]
Hi,

I would like to do a PR to expose the FixDay/FixMonth/FixDay and OpenTo parameters of `MudDatePicker`. My use case is to be able to set `FixDay="1"` and `OpenTo="OpenTo.Month"` so when a user is in the month view they can quickly choose the month they want and not have to select a day.

**Docs here:** https://mudblazor.com/components/datepicker#fixed-values-usage

Is this something that needs further discussing or is not wanted for this component?

**Comment by danheron** [comment]
That's a good idea.

I don't think it's necessary to create a new parameter - it should always work like that when in Month View.
