### ISSUE TITLE
Breaking on latest version of Mudblazor

### ISSUE THREAD

**Issue by elechijef** [danheron/Heron.MudCalendar#158]
Mudblazor has been updated to work with .net 8.0. The latest release does not work with Mudcalendar

**Comment by danheron** [comment]
The latest version of MudCalendar (2.0.0) is .Net 8.  What exactly is not working?

**Comment by danheron** [comment]
I don't have any problems with MudBlazor 7.6.0 and you don't make it easy to help you when you don't provide any information and just say that it doesn't work.

If you want to send me an example project showing the problems then I will take a look at it.

**Comment by elechijef** [comment]
I cleared my browser cache and that seemed to resolve it. Thank you for taking time to check this.
