### ISSUE TITLE
Where Do is the month of the select month or date?

### ISSUE THREAD

**Issue by ricardoromaobr** [danheron/Heron.MudCalendar#173]
I need to know the month of the select date.  Maybe a property for the current month visible in the calendar or a date select  in the CalendarDatePicker. 

I want something like this:    currentMonthVisibleOnCalendar = myCalendar.SelectedMonth;

**Comment by ricardoromaobr** [comment]
If you thing it is relevant I can do a pull request.

**Comment by danheron** [comment]
You can do this with myCalendar.CurrentDay.Month
