### ISSUE TITLE
Work Week wrong date range displayed.

### ISSUE THREAD

**Issue by TSMarcus** [danheron/Heron.MudCalendar#175]
The date picker shows the wrong date range. For instance, if the first day of the week is set to Monday and it is the 16th of September 2024, the date picker will show the date "15 - 19 SEP 2024" instead of "16 - 20 SEP 2024".

**Comment by danheron** [comment]
I'm having trouble recreating this problem.  Can you give me some more details:

- What is your default culture? (e.g. American, German etc.)
- What are you setting the FirstDayOfWeek parameter to?
- What are you setting the FirstDayOfWorkWeek parameter to?

**Comment by TSMarcus** [comment]
- What is your default culture? (e.g. American, German etc.)
      - American
   - What are you setting the FirstDayOfWeek parameter to?
      - DayOfWeek.Monday
   - What are you setting the FirstDayOfWorkWeek parameter to?
      - This parameter is not valid. I have tried with both MudCalendar and
      MudTotalCalendar. I also looked at
      https://danheron.github.io/Heron.MudCalendar/api/MudCalendar#properties
      and this parameter is not mentioned.

Additional information:

   - If I set FirstDayOfWeek to Tuesday, the same date range is given as
   with Monday. It is always the Sunday through Thursday date range no matter
   what FirstDayOfWeek is set to.
   - The "Show Code" for your example at
   https://danheron.github.io/Heron.MudCalendar/calendar#restrict-views
   does not work. No code is shown. All other examples show code.

**Comment by danheron** [comment]
Ah ok, it looks like we hadn't released the change that adds the FirstDayOfWorkWeek parameter.

I've just made a new release now (v2.0.3).  Please try this version and see if the problem still exists.

Thanks for pointing out the problem with the Restrict Views example in the docs.  This is now fixed as well.

**Comment by TSMarcus** [comment]
Thank you so much. I will try out the new version in a few hours. If you
don't hear back from me (I am so overwhelemed with work), that means the
fix worked.
