### ISSUE TITLE
String based height

### ISSUE THREAD

**Issue by digitaldirk** [danheron/Heron.MudCalendar#195]
I would like to set the calendar height to something like `calc(100vh - 25px)`. MudDataGrid allows this for example.

I haven't tested this yet so not sure if it would negatively affect the row height and such.

Willing to PR if needed.

**Comment by danheron** [comment]
Doesn't it work when you just do:

```razor
<MudCalendar style="height: calc(100vh - 25px);" />
```

Or what were you planning to change in the PR?

**Comment by digitaldirk** [comment]
```razor
<MudCalendar Style="height: calc(100vh - 25px);" />
```
This works for me - I think before I was setting some other height/min height properties and I was getting weird results with using Style. Now I am just using Style with no other height properties and it is behaving as I need.

After the next update I will do some tests to see if there would be any need for strong based height, but closing for now thanks :)
