### ISSUE TITLE
Multi Day Events

### ISSUE THREAD

**Issue by beattiesoftware** [danheron/Heron.MudCalendar#24]
When adding events over multiple days they only show on the first day. All events also do not seem to show for the whole period from start to end but just at the start time for a fixed height.

**Comment by danheron** [comment]
MudCalendar doesn't currently support multiple day events.  I will check how much work is involved in adding that.

Your second problem I can't recreate.  e.g. If you look at the first example here:  https://danheron.github.io/Heron.MudCalendar/calendar on the week/day views you can see that 'Event Today' is 1 hour long and 'Event Tomorrow' is 1.5 hours  long.  They both expand to the correct height.

Can you check that you are using the latest release?

**Comment by beattiesoftware** [comment]
Checking the events today they are correct. Apologies not sure what happened as was banging my head against a wall on that all last night.

The reason I was looking at multi day events was for potential scheduling of shifts over night. The work around for now is to book two shifts.
