### ISSUE TITLE
Send some parameters to OnClick

### ISSUE THREAD

**Issue by Gena-developer** [danheron/Heron.MudCalendar#25]
Hi, I have a question, how can I send custom my parameters to CellClicked or maybe there is another way?
for example CellClicked (DateTime dateTime, here my parameters)

**Comment by danheron** [comment]
You can't add custom parameters to the event.

Can you give me an example of a parameter you want to pass?  There is probably another way.

**Comment by Gena-developer** [comment]
I need to put id_event anywhere for each calendar event, then open my event
form with information from my database by id.

**Comment by danheron** [comment]
The way to do it would be to create a custom CellTemplate that has an OnClick event.

**Comment by Gena-developer** [comment]
Thank you very much, I really like it.
