### ISSUE TITLE
Is there a way to add localization?

### ISSUE THREAD

**Issue by LorryGailius** [danheron/Heron.MudCalendar#29]
I want to use this component in my blazor web app for a personal trainer friend so clients can book appointments, but i want the calendar to be in another language than english, how could i do that? I see there are some localization files in the repo but how do i display that and display the day names in that language?

Might as well ask this here too. If i want the user to click on the appointment he wants to book and some sort of popup i should just use CellClicked event? Doesn't CellClicked pass only the date though? I want the user to be abel to click on the CalendarItem object

**Comment by danheron** [comment]
Heron.MudCalendar is already localized into all major languages.  It will use whatever culture your web site is running under.

On the Week and Day views CellClicked will return both the day and time of the cell that was clicked.
