### ISSUE TITLE
Reference to JS and Css not added on import and not said on readme

### ISSUE THREAD

**Issue by Tarru** [danheron/Heron.MudCalendar#30]
I currently am running on .net7 and have installed the library using nugget package manager or by hand with command promp dotnet add command.
![image](https://github.com/danheron/Heron.MudCalendar/assets/44491813/5130cfaa-9233-4a54-9751-fb921110edcb)
![image](https://github.com/danheron/Heron.MudCalendar/assets/44491813/a387dd53-41f2-4d98-a42f-596f73c4cd5b)
As you will see in this screenshot, the calendar is here but seems to have no CSS nor JS included with the package.
I can't find any reference to the JS or CSS in my Index.html file either

link href="_content/Heron.MudCalendar/Heron.MudCalendar.min.css" rel="stylesheet" 
script src="_content/Heron.MudCalendar/Heron.MudCalendar.js"

Those line made the library work but are not mentioned in any of the readme files.

How I used the lib : 
Installed via Nugget
Added the import (like in the readme)
Added the <mudCallendar /> in my file as described by the readme.

**Comment by danheron** [comment]
The links should be injected into the page as needed.  However someone has reported that this doesn't work when running in Maui.

Can you tell me:  Are you using Blazor Server or WebAssembly?  Anything unusual about your project setup?

I will try to find out why this sometimes doesn't work.

**Comment by Tarru** [comment]
Hi again, sorry for the delay I did not get the notification ....
My project is in Blazor WASM, the setup is as when you create a new blazor project.
My idea could be that i'm using mudblazor and that may be an issue ? But it does not change the Index.html location...
 
You could just provide a troubleshooting scenario in the Read me in case people have the same issue as me so they check for this issue ?

**Comment by REDECODE** [comment]
Same for me. 
I'm using Blazor Server on .Net7.

I've solved explicitly adding links to css and js in Host.cshtml

**Comment by danheron** [comment]
OK, I'll add it to the readme.
