### ISSUE TITLE
Double DateRangeChanged event on previous/next clicked

### ISSUE THREAD

**Issue by alisson-d-s** [danheron/Heron.MudCalendar#33]
When you navigate with the DatePicker, runs Invoke only one DateRangeChanged event, but with the previous/next buttons, it runs twice.

Using an example from the documentation, you can reproduce this behavior:
Loading Data exemple

```
@inject EventService EventService

<MudCalendar Items="_events" MonthCellMinHeight="100" DateRangeChanged="DateRangeChanged" />
@code{

    private List<CalendarItem> _events = new();

    private void DateRangeChanged(DateRange dateRange)
    {
        // Load events from service
        _events = EventService.GetEvents(dateRange);
    }
}
```

If you put a Console.Write() in the EventCallback, you gonna see that the Event runs twice.

A workaround that i found, was override the method removing the DateRangeChanged Invoke:
```
protected override Task OnPreviousClicked()
    {
        CurrentDay = View switch
        {
            CalendarView.Day => CurrentDay.AddDays(-1),
            CalendarView.Week => CurrentDay.AddDays(-7),
            CalendarView.Month => CurrentDay.AddMonths(-1),
            _ => CurrentDay
        };
        
        return Task.Delay(1);
}
```

I don't know if this is optimal but works great.
it seems that when changing the CurrentDay, already Invoke the event.

**Comment by danheron** [comment]
Thanks for reporting that, I'll take a look at it.
