### ISSUE TITLE
Allow arbitrary DayTimeInterval's

### ISSUE THREAD

**Issue by JeremyEspresso** [danheron/Heron.MudCalendar#56]
Awesome library thank you so much!

Currently a library consumer is forced to use any of the intervals as specified in:
https://github.com/danheron/Heron.MudCalendar/blob/4f6e4f9c4f825a51e94ecca49ac7fa9dbd91c07c/Heron.MudCalendar/Enums/CalendarTimeInterval.cs#L3-L8

For the project I am currently working on I would preferably have a custom interval of 3 hours.
Let me know if this is something I can pickup and what the preferred way would be to implement this.

Thanks!

**Comment by danheron** [comment]
It's difficult to change it to an arbitrary amount now as it would break backwards compatibility.  However I will add some more options to the enum including an option for 3 hours.

**Comment by JeremyEspresso** [comment]
Thank you @danheron! I appreciate it!
