### ISSUE TITLE
Add Event Callback for Item Click

### ISSUE THREAD

**Issue by traseedarkwatch** [danheron/Heron.MudCalendar#63]
There's an event callback for a Cell Click, but nothing for the Item Clicked. If there are multiple items on a day, it would be useful to have a callback for clicking on the item so a dialog could be opened to view the details of the event. This would be useful for integration with other calendar APIs such as Google or Outlook Calendar, for showing additional information about the event.

**Comment by MinZe25** [comment]
https://github.com/danheron/Heron.MudCalendar/pull/66

**Comment by danheron** [comment]
Merged pull request that fixes the issue.
