### ISSUE TITLE
JS Loading not Exist and when I moved Next or Previous Exception throw WS SignalR problem

### ISSUE THREAD

**Issue by MinaShokralla** [danheron/Heron.MudCalendar#77]
Hi,

I faces two problem one that the JS is not found as attached screenshots

I managed to have the script manually and I face other problem when I moved between days or months after multiple click I receive an exception related to SignalR WS, it is look like the component disposed and lost the track

attached screenshots
![Error Details](https://github.com/danheron/Heron.MudCalendar/assets/31363903/142ed4e5-8759-491f-a009-e8e08d9cf15e)
![JS not found](https://github.com/danheron/Heron.MudCalendar/assets/31363903/741c8abe-3a13-46c9-a8a5-1856690fa341)
![JS register](https://github.com/danheron/Heron.MudCalendar/assets/31363903/d574e6b6-5893-461a-a079-19fa71f5b5b9)

and thanks for your great Calendar :)

**Comment by MinaShokralla** [comment]
I got the problem, the End date was the same as a start date, that is the reasons it is throw exceptions 
Thanks a lot again for your great work

**Comment by danheron** [comment]
OK, thanks for letting me know that you found the problem.  I should probably add a check for that.
