### ISSUE TITLE
Current Time Marker

### ISSUE THREAD

**Issue by APusch-Tenno** [danheron/Heron.MudCalendar#79]
hi,
since there are not many (paid and free) alternatives out there for a scheduler in MudBlazor and this one is fitting my needs quite well, I really want to make this work.

unfortunately I've come across a few issues.

one of these is that the marker for the current time is not displaying at the correct spot.
with half hour view the marker is always jumping to the next half hour.
in 15 minute view it is always between the grid lines and for each quarter hour it jumps half a grid field ahead and then stays there until the time hits the next quarter hour.

I have another major issue, but I will open a new ticket for that.

thanks for creating this scheduler/calendar and I hope these issues can get fixed.

**Comment by danheron** [comment]
I can't recreate this problem - it always looks correct to me.

Do you see this problem in the example on the docs page?  If yes, then what browser are you using?

**Comment by APusch-Tenno** [comment]
yes, in the docs page it is always jumping ahead between the lines, no matter what setting I use. for some reason in my project it jumps only on the lines, but still shows the incorrect time:
![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/a0552d3a-fd3b-4f9d-b713-8da663129773)


I tested the doc page with different browsers (Edge, Chrome, Firefox), time was 8:40 am:
![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/21a9b2b0-487d-41ca-9f98-35e241c2e65b)

could this be a localization issue? I'm in germany.
but I don't see why my project shows something different, while on the same machine (separate VM) it shows the same behavior on the doc page.
either way neither shows the correct time.

**Comment by danheron** [comment]
Yes, it is a localisation issue.  I will fix that.

**Comment by APusch-Tenno** [comment]
thanks

**Comment by APusch-Tenno** [comment]
I have inserted the fixed code in my project, but unfortunately the time is still not correctly showing, although now the marker seems to move with each minute.

Actual time here is 11:24:
![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/8be8bc64-cc3f-4d2d-8c88-fc777cc32f37)
![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/b3d737f4-48d4-4a96-9f81-3fad3ea8224d)

It seems so be shifted by about 10 minutes now.

Sorry for bothering.

**Comment by danheron** [comment]
Do you still have this problem?  In the example you sent me it looks correct.  Do you have the problem in all browsers?

**Comment by APusch-Tenno** [comment]
Yes, the problem is still there, but as written before, the marker now moves with each minute.

![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/4e35c5fd-dd50-4d42-ab4f-46ff3e97d3f8)
actual time was 16:20 (I think it is showing 16:35, so it is shifted 15 minutes with each minute)

tested in Firefox, Chrome and Edge, same result

**Comment by danheron** [comment]
That's very strange I can't replicate this problem.  Could you try debugging it yourself and see if you can find the problem.

**Comment by APusch-Tenno** [comment]
As you might have figured out, I'm quite new to Blazor, but I managed to figure out, that the shift is always exactly half of the set interval, so +5 when in 10 minute interval and +30 when in 60 minute interval.

For now I fixed my indicator by changing TimelinePosition() in DayWeekViewBase.razor.cs
from this
`var minutes = (int)Math.Floor(DateTime.Now.Subtract(DateTime.Today).TotalMinutes) - (TimelineRow() * (int)Calendar.DayTimeInterval);`
to this
`var minutes = DateTime.Now.Subtract(DateTime.Today).TotalMinutes - (TimelineRow() * (int)Calendar.DayTimeInterval) - (int)Calendar.DayTimeInterval / 2;`

But obviously this is not a general fix.
I don't see why the localization is changing the outcome, since DateTime.Now already gives the local date and time.
I tried changing DateTime.Today to DateTime.Today.ToLocalTime(), which again puts the indicator right in the middle of the interval lines. 

Maybe you can figure out more with this information.
If not I will leave it like that, because this page is not supposed to be used outside this timezone.

**Comment by danheron** [comment]
Where do you get this code from?  The code in TimelinePosition() has never included Math.Floor().

The localization changes the output because some cultures use , as a decimal point and some cultures use .
The fix I applied was to use TimelinePosition().ToInvariantString() in the StyleBuilder() function.
