### ISSUE TITLE
Height Container Number

### ISSUE THREAD

**Issue by mariajesusborrego** [danheron/Heron.MudCalendar#87]
I need the 'container' that holds the month number to be smaller so that the content of the day is better visualized.
![image](https://github.com/danheron/Heron.MudCalendar/assets/150235095/2e63be48-7d75-40a9-88f4-301e4d4675fa)

**Comment by danheron** [comment]
The class name of that container is mud-cal-month-cell-title.  It has a padding on all sides of 8px.  You could reduce the padding like this:

```css
.mud-cal-month-cell-title {
  padding: 2px;
}
```
