### ISSUE TITLE
Enable/Disable Scrolling in Cell

### ISSUE THREAD

**Issue by KevinKrueger** [danheron/Heron.MudCalendar#93]
Parameter: EnableInCellScrolling

![image](https://github.com/danheron/Heron.MudCalendar/assets/25382167/acdb78b5-f875-469d-b641-bdefc9fe6d72)

**Comment by danheron** [comment]
If you disable the scrolling then how would you see the events?

**Comment by danheron** [comment]
Closing because no response.
