### ISSUE TITLE
Month view formatting with multiple appointments per day

### ISSUE THREAD

**Issue by APusch-Tenno** [danheron/Heron.MudCalendar#97]
Hello again,

while testing I just noticed another formatting issue and also differences between browsers (possibly related to the formatting issue with Firefox).

When having multiple appointments in one day, in Firefox it causes the day field to stretch, which also stretches the whole line:

![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/4ae1f20e-e228-4530-b8da-927cc657dc7e)

The more appointments are added, the more it is making the lowest line to shift out of frame, so the fields are not visible/accessable.

On the other hand in Chrome it shows a scrollbar (which is fine), but I also have empty scrollbars on all the other fields:

![grafik](https://github.com/danheron/Heron.MudCalendar/assets/107390850/70f9e3a0-7bfa-4e41-b4d5-f4fd85c6f957)

I don't know, if this is a side effect of the height adjustment you suggested me to do earlier, but I suppose it shouldn't have a different effect per browser.

**Comment by danheron** [comment]
Yes, I think this is another firefox issue.

**Comment by danheron** [comment]
No, empty scrollbars are not correct.  I will take a look at that.

**Comment by danheron** [comment]
This is fixed by #114
